app:
#  topic: 'multi-partition-topic'
  topic: 'working-with-json'

# creating a topic with multi-partitions : inside the config folder exec the commands with param below
#  ./kafka-topics.sh
#  --bootstrap-server localhost:9092
#  --create --topic multi-partition-topic
#  --partitions 3
#  --replication-factor 1

# describe a topic:
#  ./kafka-topics.sh
#  --bootstrap-server localhost:9092
#  --describe
#  --topic multi-partition-topic

# Results:
# Topic: multi-partition-topic	PartitionCount: 3	ReplicationFactor: 1	Configs: segment.bytes=1073741824
#       Topic: multi-partition-topic	Partition: 0	Leader: 0	Replicas: 0	Isr: 0
#       Topic: multi-partition-topic	Partition: 1	Leader: 0	Replicas: 0	Isr: 0
#       Topic: multi-partition-topic	Partition: 2	Leader: 0	Replicas: 0	Isr: 0